name: migr
recipe: drupal8

proxy:
  d7simple_php:
    - d7simple.migr.lndo.site

services:
  appserver:
    type: php:7.4
    via: apache
    webroot: d9/web
  database:
    type: mariadb:10.4
    overrides:
      image: bitnami/mariadb:10.4
  cache:
    type: redis:5

  d7simple_php:
    type: php:7.3
    via: apache
    webroot: d7simple
    build_as_root:
      - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush/releases/download/8.3.3/drush.phar
      - chmod +x /usr/local/bin/drush
  d7simple_db:
    type: mariadb:10.4
    webroot: d7complex
    overrides:
      image: bitnami/mariadb:10.4

tooling:
  drush:
    service: appserver
    cmd: /app/d9/vendor/bin/drush
  redis-cli:
    service: cache

config:
  conf:
    php: .lando/php.ini
