name: migr
recipe: drupal8

proxy:
  d7simplephp:
    - d7simple.migr.lndo.site
  d7complexphp:
    - d7complex.migr.lndo.site

services:
  appserver:
    type: php:7.4
    via: apache
    webroot: d9/web
  database:
    type: mariadb:10.4
    overrides:
      image: bitnami/mariadb:10.4
  cache:
    type: redis:5

  d7simplephp:
    type: php:7.3
    via: apache
    webroot: d7simple
    build:
      - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush/releases/download/8.4.5/drush.phar
      - chmod +x /usr/local/bin/drush
  d7simpledb:
    type: mariadb:10.4
    overrides:
      image: bitnami/mariadb:10.4

  d7complexphp:
    type: php:7.3
    via: apache
    webroot: d7complex
    build:
      - wget -O /usr/local/bin/drush https://github.com/drush-ops/drush/releases/download/8.4.5/drush.phar
      - chmod +x /usr/local/bin/drush
  d7complexdb:
    type: mariadb:10.4
    overrides:
      image: bitnami/mariadb:10.4

tooling:
  drush:
    service: appserver
    cmd: /app/d9/vendor/bin/drush
  redis-cli:
    service: cache

config:
  conf:
    php: .lando/php.ini
